name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: pg-telemetry-bulk-loader
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          pg-telemetry-bulk-loader/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('pg-telemetry-bulk-loader/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Lint with clippy
      run: cargo clippy -- -D warnings
      
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    defaults:
      run:
        working-directory: ./pg-telemetry-bulk-loader  # Путь к проекту
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Build
      run: cargo build --release --verbose
    
    - name: Run tests
      run: cargo test --verbose
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pg-telemetry-bulk-loader-${{ matrix.os }}
        path: pg-telemetry-bulk-loader/target/release/pg-telemetry-bulk-loader*
